project_id = "eftkbldhggrknfmmcimc"

[functions.create-first-admin]
verify_jwt = false

[functions.get-user-email]
verify_jwt = false

[functions.check-admin-exists]
verify_jwt = false

[functions.validate-ticket-api]
verify_jwt = false
