project_id = "eftkbldhggrknfmmcimc"

[api]
enabled = true
port = 54321

[db]
port = 54322

[functions.validate-ticket-api]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.cleanup-orphan-users]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.update-user-profile]
verify_jwt = false
